export const currentHiveTypes = {
    GET_HIVE: 'GET_HIVE',
    CLEAR_HIVE: 'CLEAR_HIVE',
    GET_ID: 'GET_ID',
    CREATE_NEW_LIST: 'CREATE_NEW_LIST',
    CREATE_NEW_TASK: 'CREATE_NEW_TASK',
    DELETE_TASK: 'DELETE_TASK',
    DELETE_LIST: 'DELETE_LIST',
    UPDATE_TASK: 'UPDATE_TASK',
    UPDATE_LIST: 'UPDATE_LIST',
}